### PR TITLE
make smtp username and password optional

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by cnryb** [comment]
How to send email without username and password ?

**Comment by viosys** [comment]
when you use an internal exchange server without auth.

**Review by cnryb — APPROVED** [review]
LGTM

**Comment by viosys** [comment]
I just found that I think I forgot to increase the version of the extension itself.
Could you increase it?

**Comment by cnryb** [comment]
OK, I got it.

**Comment by cnryb** [comment]
Published, you can try it.

**Comment by viosys** [comment]
thank's, i will try

**Pull request merged**
